name: build

on: push

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-20.04, cc: clang-12, cxx: clang++-12 }
          - { os: ubuntu-20.04, cc: gcc-10, cxx: g++-10 }
          - { os: macos-10.15, cc: clang, cxx: clang++ }
          - { os: windows-2019 }
    steps:
      - name: set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install conan

      - name: setup odr conan repo
        run: |
          conan remote remove conancenter
          conan remote add odr-conan-repo https://odr.jfrog.io/artifactory/api/conan/odr-conan
          conan remote add conancenter: https://center.conan.io
          conan config set general.revisions_enabled=1
          conan user -p "${{ secrets.JFROG_PASSWORD }}" -r odr-conan-repo "${{ secrets.JFROG_USERNAME }}"

      - name: checkout
        uses: actions/checkout@v2

      - run: conan export recipes/fontforge/conanfile.py
      - run: conan export recipes/libuninameslist/conanfile.py
      - run: conan export recipes/pdf2htmlEX/conanfile.py
      - run: conan export recipes/poppler/conanfile.py
      - run: conan export recipes/spiro/conanfile.py

      - run: conan create --build=missing recipes/fontforge/conanfile.py
      - run: conan create --build=missing recipes/libuninameslist/conanfile.py
      - run: conan create --build=missing recipes/pdf2htmlEX/conanfile.py
      - run: conan create --build=missing recipes/poppler/conanfile.py
      - run: conan create --build=missing recipes/spiro/conanfile.py

      - run: conan upload fontforge -r odr-conan-repo -c
      - run: conan upload libuninameslist -r odr-conan-repo -c
      - run: conan upload pdf2htmlEX -r odr-conan-repo -c
      - run: conan upload poppler -r odr-conan-repo -c
      - run: conan upload spiro -r odr-conan-repo -c
