name: build

on: push

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-22.04, profile: ubuntu-22.04-clang, }
          - { os: ubuntu-20.04, profile: ubuntu-20.04-clang, }
          - { os: macos-10.15, profile: macos-10.15-clang, }
          - { os: windows-2019, profile: windows-2019-msvc, }
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: pip install conan

      - name: conan setup
        run: |
          conan remote remove conancenter
          conan remote add odr-conan-repo https://odr.jfrog.io/artifactory/api/conan/odr-conan
          conan remote add conancenter: https://center.conan.io
          conan config set general.revisions_enabled=1
          conan user -p "${{ secrets.JFROG_PASSWORD }}" -r odr-conan-repo "${{ secrets.JFROG_USERNAME }}"
          conan profile new default --detect

      - name: conan profile
        if: startsWith(matrix.config.os, 'ubuntu') || startsWith(matrix.config.os, 'macos')
        run: cp profiles/${{ matrix.config.profile }} ~/.conan/profiles/default
      - name: conan profile
        if: startsWith(matrix.config.os, 'windows')
        run: cp profiles/${{ matrix.config.profile }} C:/Users/runneradmin/.conan/profiles/default

      - name: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.conan/data
            C:/Users/runneradmin/.conan/data
          key: ${{ matrix.config.os }}-rev1
          restore-keys: |
            ${{ matrix.config.os }}-

      - run: conan export recipes/fontforge/conanfile.py
      - run: conan export recipes/libuninameslist/conanfile.py
      - run: conan export recipes/pdf2htmlEX/conanfile.py
      - run: conan export recipes/poppler/conanfile.py
      - run: conan export recipes/spiro/conanfile.py

      - run: conan create --build=missing recipes/pdf2htmlEX/conanfile.py

      - run: conan upload pdf2htmlEX -r odr-conan-repo -c
