name: build

on: push

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-22.04, profile_host: ubuntu-22.04-clang, profile_build: ubuntu-22.04-clang, }
          - { os: ubuntu-22.04, profile_host: ubuntu-22.04-android-armv8, profile_build: ubuntu-22.04-clang, }
          - { os: ubuntu-20.04, profile_host: ubuntu-20.04-clang, profile_build: ubuntu-20.04-clang, }
          - { os: macos-10.15, profile_host: macos-10.15-clang, profile_build: macos-10.15-clang, }
          - { os: windows-2019, profile_host: windows-2019-msvc, profile_build: windows-2019-msvc, }
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: pip install conan

      - name: conan profiles
        run: |
          conan profile new default
          cp profiles/* "$(conan config home)/profiles"

      - name: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.conan/data
            C:/Users/runneradmin/.conan/data
          key: ${{ matrix.config.profile_build }}-${{ matrix.config.profile_host }}-rev1
          restore-keys: |
            ${{ matrix.config.profile_build }}-${{ matrix.config.profile_host }}-

      - run: conan export recipes/fontforge/conanfile.py
      - run: conan export recipes/libuninameslist/conanfile.py
      - run: conan export recipes/pdf2htmlEX/conanfile.py
      - run: conan export recipes/poppler/conanfile.py
      - run: conan export recipes/spiro/conanfile.py

      - run: conan create --build=missing --profile:host=${{ matrix.config.profile_host }} --profile:build=${{ matrix.config.profile_build }} recipes/pdf2htmlEX/conanfile.py

      #- name: conan setup
      #  run: |
      #    conan remote add odr-conan-repo https://odr.jfrog.io/artifactory/api/conan/odr-conan
      #    conan config set general.revisions_enabled=1
      #    conan user -p "${{ secrets.JFROG_PASSWORD }}" -r odr-conan-repo "${{ secrets.JFROG_USERNAME }}"

      #- run: conan upload pdf2htmlEX -r odr-conan-repo -c
